name: Backend CI # ワークフロー名を具体的にしました

on:
  push:
    branches:
      - master # main ブランチを使用している場合は 'main' に変更してください
  pull_request:
    branches:
      - master # main ブランチを使用している場合は 'main' に変更してください

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Change to backend directory # ディレクトリ移動のステップを明確にしました
        run: cd backend # run キーワードの下に直接コマンドを記述します

      - name: Setup Rust toolchain # Rustツールのセットアップを追加
        uses: dtolnay/rust-toolchain@stable # これがないとcargoコマンドが使えません

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
